on:
  push:
  pull_request:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Cargo test"
        run: cargo test --all

  format:
    name: "Check rustfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Rustfmt check"
        run: cargo fmt --check

  clippy:
    name: "Check clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Clippy check"
        run: cargo clippy --all-targets --all-features
